name: Run ETL and Upload Data to S3

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
    # - cron: "*/2 * * * *"
    # - cron: "0 0 * * *"

  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - opened
  #     - synchronize
  #     - reopened
  #   paths-ignore:
  #     - '**.md'

  

jobs:
  etl-job:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET: scale-etl-bucket-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run ETL script
        working-directory: etl
        run: |
          echo "Running ETL pipeline..."
          python etl.py
          echo "ETL complete."
      
      - name: Run duel generation + analytics
        working-directory: app
        run: python duel_pipeline.py

